const translations = {
    "pt-BR": {
      raccounter: "Raccounter",
      dashboard: "Dashboard",
      home: "Home",
      getPDF: "Baixar PDF",
      inUse: "EM uso",
      people: "Pessoas",
      dailyTotal: "Total diário",
      mostUsedRooms: "Salas mais usadas",
      code: "Código",
      quantity: "Quantidade",
      capacity: "Lotação",
      completed: "Concluído",
      pending: "Pendente",
      process: "Em processo",
      todos: "Tarefas",
      checkInventory: "Checar estoque",
      manageDelivery: "Gerenciar equipe de entrega",
      contactSelma: "Contato com Selma: Confirmar entrega",
      updateCatalogue: "Atualizar catálogo da loja",
      countProfit: "Contar análise de lucro"
    },
    "en": {
      raccounter: "Raccounter",
      dashboard: "Dashboard",
      home: "Home",
      getPDF: "Get PDF",
      inUse: "In Use",
      people: "People",
      dailyTotal: "Daily Total",
      mostUsedRooms: "Most Used Rooms",
      code: "Code",
      quantity: "Quantity",
      capacity: "Capacity",
      completed: "Completed",
      pending: "Pending",
      process: "Process",
      todos: "Todos",
      checkInventory: "Check Inventory",
      manageDelivery: "Manage Delivery Team",
      contactSelma: "Contact Selma: Confirm Delivery",
      updateCatalogue: "Update Shop Catalogue",
      countProfit: "Count Profit Analytics"
    },
    "es": {
      raccounter: "Raccounter",
      dashboard: "Panel",
      home: "Inicio",
      getPDF: "Descargar PDF",
      inUse: "En uso",
      people: "Personas",
      dailyTotal: "Total diario",
      mostUsedRooms: "Salas más usadas",
      code: "Código",
      quantity: "Cantidad",
      capacity: "Capacidad",
      completed: "Completado",
      pending: "Pendiente",
      process: "En proceso",
      todos: "Tareas",
      checkInventory: "Verificar inventario",
      manageDelivery: "Gestionar equipo de entrega",
      contactSelma: "Contactar a Selma: Confirmar entrega",
      updateCatalogue: "Actualizar catálogo de tienda",
      countProfit: "Contar análisis de ganancias"
    }
  };
  